# Generated by Django 4.0.6 on 2022-09-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=400)),
                ('destinatario', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
