# Generated by Django 4.0.6 on 2022-09-05 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='fecha',
        ),
    ]
