# Generated by Django 4.0.6 on 2022-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Dni', models.IntegerField()),
                ('Curso', models.CharField(max_length=50)),
                ('Telefono', models.IntegerField()),
            ],
        ),
    ]
