# Generated by Django 4.0.6 on 2022-09-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tu_nombre', models.CharField(max_length=30)),
                ('Seleccionar_curso', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Valoracion', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='Camada',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre',
            new_name='Nombre',
        ),
    ]
