# Generated by Django 4.0.6 on 2022-09-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0003_comentarios_rename_camada_curso_camada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='Seleccionar_curso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='Valoracion',
            field=models.CharField(max_length=30),
        ),
    ]
